### ISSUE TITLE
Error al suscribirse a la lista de correo

### ISSUE THREAD

**Issue by Juanlu001** [HackCancer/hackcancer#5]
Error 500:
![screenshot_20171101-110940](https://user-images.githubusercontent.com/316517/32270258-714bd9bc-bef5-11e7-8e89-3fe8e436c828.png)

**Comment by oiertwo** [comment]
Es un error de redireccion, pero te subscribes bien. Tenemos la web caída... no es parte del evento XD

**Comment by Juanlu001** [comment]
Oído. Me alegro de haberme suscrito bien en cualquier caso xD
